version: '3.3'

services:

# Configuration Services
        servicediscovery:
                build: ./servicediscovery
                container_name: servicediscovery
                ports: 
                        - "8761:8761"
        api-gateway:
                build: ./api-gateway
                container_name: api-gateway
                ports:
                        - "8080:8080"
                depends_on:
                        - servicediscovery
                        - db-general

# MicroServices
        ambienteservice:
                build: ./ambienteservice
                container_name: ambienteservice
                depends_on:
                        - api-gateway
                        - db-general
        cursoservice:
                build: ./cursoservice
                container_name: cursoservice
                depends_on:
                        - api-gateway
                        - db-general
        coordenadorservice:
                build: ./coordenadorservice
                container_name: coordenadorservice
                depends_on:
                        - api-gateway
                        - db-general
        professorservice:
                build: ./professorservice
                container_name: professorservice
                depends_on:
                        - api-gateway
                        - db-general
        horarioservice:
                build: ./horarioservice
                container_name: horarioservice
                depends_on:
                        - api-gateway
                        - db-general

# Databases
        db-general:
                build: ./database
                container_name: database
                ports:
                        - "5433:5432"
