# https://github.com/elastic/logstash-docker
# FROM docker.elastic.co/logstash/logstash-oss:6.7.0
FROM logstash:6.7.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
